### ISSUE TITLE
leaflet_1.default.maplibreGL is not a constructor

### ISSUE THREAD

**Issue by krasnoludkolo** [ted-piotrowski/react-leaflet-vector-tile-layer#10]
Hello, 
I'm trying to use 
```
        <VectorTileLayer
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            styleUrl="https://api.maptiler.com/maps/<map_id>/style.json?key=<key>"
        />
```

and I got

```
leaflet_1.default.maplibreGL is not a constructor
TypeError: leaflet_1.default.maplibreGL is not a constructor
    at createTileLayer (http://localhost:3000/static/js/bundle.js:113008:15)
    at useMutableLeafletElement (http://localhost:3000/static/js/bundle.js:138229:51)
    at useLayer (http://localhost:3000/static/js/bundle.js:138470:24)
    at LeafComponent (http://localhost:3000/static/js/bundle.js:138029:9)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:101062:22)
    at updateForwardRef (http://localhost:3000/static/js/bundle.js:103631:24)
    at beginWork (http://localhost:3000/static/js/bundle.js:105678:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:90658:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:90702:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:90759:35)
```

Is there anything I'm doing wrong? 

related packages 

```
    "@types/react-leaflet": "^3.0.0",
    "leaflet": "^1.9.4"
    "react-leaflet": "^4.2.1",
    "react-leaflet-vector-tile-layer": "^0.2.1",
```

**Comment by ted-piotrowski** [comment]
It looks correct. I updated the dependencies today so you can try again and maybe the issue is fixed otherwise you'll need to share more of your code/configuration.

**Comment by ted-piotrowski** [comment]
Okay, I found the issue and fixed it. Please update to the latest version 0.3.2 and it should work now.

**Comment by krasnoludkolo** [comment]
I can confirm, it works now! Thanks
